[build]
# make final binary statically linked against libc
rustflags = ["-Ctarget-feature=+crt-static"]
target = ["x86_64-unknown-linux-gnu", "bpfel-unknown-none"]

[alias]
# replace with the target triple you are developing on must be the same as
# as the other target than bpf specified in build.target
xtask = "run -q --target=x86_64-unknown-linux-gnu --package xtask --release --"
xrun = "xtask run"
xbuild = "xtask build"
xrelease = "xtask release"
